### ISSUE TITLE
Document how to use with Self-Hosted Pulumi Service

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-kubernetes-operator#105]
### Problem description

Should document how to use the operator with a [Self-Hosted Pulumi Service](https://www.pulumi.com/docs/guides/self-hosted/) - e.g. `pulumi login https://api.pulumi.example.com`.

**Comment by pgavlin** [comment]
@clstokes how important/urgent is this?

**Comment by clstokes** [comment]
This is solved with https://github.com/pulumi/pulumi-kubernetes-operator/pull/106.

https://github.com/pulumi/pulumi-kubernetes-operator/blob/bd45f50c3412903480a549db51c4229d2d8f1e54/deploy/crds/pulumi.com_stacks.yaml#L38-L40

For example: 

```
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
type: Opaque
stringData:
  accessToken: "<REDACTED: PULUMI_ACCESS_TOKEN>"
---
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: nginx-k8s-stack
spec:
  accessTokenSecret: pulumi-api-secret
  backend: https://api.pulumi.example.com                           # <- this line
  stack: joeduffy/nginx/dev
  projectRepo: https://github.com/metral/pulumi-nginx
  commit: 2b0889718d3e63feeb6079ccd5e4488d8601e353
  destroyOnFinalize: true
```
