### ISSUE TITLE
Operator logs sensitive information on info level

### ISSUE THREAD

**Issue by sfc-gh-jelsesiy** [pulumi/pulumi-kubernetes-operator#140]
The operator allows reading various configuration items via `ResourceRef` which is great. However, upon retrieving the configs from the Stack CR it logs all values on `info` causing secrets leakage.

## Expected behavior

If these configs need to be logged at all, either mask these values before doing so or increase logging verbosity to `debug`.

## Current behavior

Secrets leak on `info`. Also the operator default manifests set the level to `debug`, see https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/deploy/yaml/operator.yaml#L23

## Steps to reproduce

1. Deploy operator
2. Deploy stack

```
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: stack
  namespace: pulumi-operator
spec:
  commit: xzy
  envRefs:
    PULUMI_ACCESS_TOKEN:
      filesystem:
        path: /path/to/pulumi_api_token
      type: FS
...
```

3. Observe log emitting all stack properties on `info`.
