### ISSUE TITLE
repoDir not working

### ISSUE THREAD

**Issue by universam1** [pulumi/pulumi-kubernetes-operator#145]
Only stack files at the root of the repo are working, subdirs using `repoDir` property fails

## Expected behavior
moving the stack files in a subdir and defining the directory via `repoDir` should work

## Current behavior
error:
```json
{
    "level": "error",
    "ts": 1620396804.025099,
    "logger": "controller-runtime.controller",
    "msg": "Reconciler error",
    "controller": "stack-controller",
    "name": "sams-elasticache",
    "namespace": "default",
    "error": "failed to resolve git repository from working directory: /tmp/pulumi_auto521021910/testfolder: repository does not exist",
    "errorVerbose": "repository does not exist
    failed to resolve git repos itory from working directory: /tmp/pulumi_auto521021910/testfolder
    github.com/pulumi/pulumi-kubernetes-operator/pkg/controller/stack.revisionAtWorkingDir
        /home/runner/work/pulumi-kubernetes-operator/pulumi-kubernetes-operator/pkg/controller/stack/stack_controller.go:643
    github.com/pulumi/pulumi-kubernetes-operator/pkg/controller/stack.(*ReconcileStack).Reconcile
        /home/runner/work/pulumi-kubernetes-operator/ pulumi-kubernetes-operator/pkg/controller/stack/stack_controller.go:162
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1-0.20200724132623-e50c7b819263/pkg/internal/controller/controller.go:233
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/go/pkg/mod/sigs. k8s.io/controller-runtime@v0.6.1-0.20200724132623-e50c7b819263/pkg/internal/controller/controller.go:209
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1-0.20200724132623-e50c7b819263/pkg/internal/controller/controller.go:188
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /home/runner/go/pkg/mod/k8s.io/apimachiner y@v0.18.4/pkg/util/wait/wait.go:155
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:156
    k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:133
    k8s.io/apimachinery/pkg/util/wait.Until
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:90
    run time.goexit
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/asm_amd64.s:1371",
    "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error
        /home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1-0.20200724132623-e50c7b819263/pkg/internal/controller/contr oller.go:235
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1-0.20200724132623-e50c7b819263/pkg/internal/controller/controller.go:209
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1-0.20200724132623-e50c7b819263/pkg/in ternal/controller/controller.go:188
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:155
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:156
    k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wa it.go:133
    k8s.io/apimachinery/pkg/util/wait.Until
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:90"
}
```

## Steps to reproduce
cr:
```yaml
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: sams-elasticache
spec:
  envRefs:
    AWS_REGION:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_REGION
    AWS_DEFAULT_REGION:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_REGION
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_SECRET_ACCESS_KEY
    PULUMI_CONFIG_PASSPHRASE:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: PULUMI_CONFIG_PASSPHRASE
  stack: elasticache
  config:
    aws:region: us-east-1
  projectRepo: https://github.com/universam1/pulumi-operator
  commit: 4679d57095f4b54862afad0f9d9c9e5d193a51bd
  repoDir: testfolder
```

However using commit 41c3d56d77f02a3a1595f4f453514c614fd1b2fa that is on the root of the project it works as expected

## Context (Environment)
impossible to try these examples https://github.com/pulumi/examples

## Affected feature
mono-repos are impossible with this bug
