### ISSUE TITLE
Python virtualenv option within stack definition malfunctioning

### ISSUE THREAD

**Issue by gkramer** [pulumi/pulumi-kubernetes-operator#174]
The K8s Operator is unable to handle python 'virtualenv' directory option - it attempts to find directory in /venv, rather than /tmp/<tmp-checkout-dir>/venv.

## Steps to reproduce
1. Utilise a current version of Pulumi, and Pulumi K8s Operator (turn up debugging!)
2. Attempt to deploy a python runtime stack with 'runtime.options.virtualenv' = venv

i.e. Pulumi.yaml file:
```yaml
name: example
runtime:
  name: python
  options:
    virtualenv: venv
```

Expected:
A new, happy stack!

Actual output:
{"level":"debug","ts":1628722967.6071494,"logger":"controller_stack","msg":"Pip Install","Request.Namespace":"default","Request.Name":"bow-poc","Path":"/usr/local/bin/python3","Args":["/usr/local/bin/python3","-m","venv","venv"],"Text":"Error: [Errno 13] Permission denied: '/venv'"}

Based on the debug message, it appears as if the operator does not CWD into the stack repo directory (created in /tmp/<random-dir> before attempting to create the venv directory. I'm assuming this is a simple case of forgetting to prefix the venv directory with the repo checkout dir.

**Comment by viveklak** [comment]
@gkramer are you running with the pulumi-kubernetes-operator docker images https://hub.docker.com/r/pulumi/pulumi-kubernetes-operator/tags?page=1&ordering=last_updated? FWIW I tried this with a few of the python [examples](https://github.com/pulumi/examples/tree/master/aws-py-s3-folder) with the vanilla v0.0.16/17 releases(which all use venv) and things worked fine, .e.g:

```
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
type: Opaque
stringData:
  accessToken: "<Redacted>"
---
apiVersion: v1
kind: Secret
metadata:
  name: pulumi-aws-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<Redacted>"
  AWS_SECRET_ACCESS_KEY: "<Redacted>"
  AWS_SESSION_TOKEN: "<Redacted>"
---
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: s3-bucket-stack
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_SESSION_TOKEN
  stack: vivek/aws-py-s3-folder/dev
  projectRepo: https://github.com/pulumi/examples
  repoDir: aws-py-s3-folder
  branch: refs/heads/master
  config:
    aws:region: us-west-2
```
