### ISSUE TITLE
Config structure unable to accept maps

### ISSUE THREAD

**Issue by xwang0818** [pulumi/pulumi-kubernetes-operator#184]
## Summary:
The config section under the Stack CRD needs to be able to accept a map. E.g.:
```
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: stack-name
spec:
  config:
    aws:region: us-east-2
    aws:assumeRole:
      roleArn: arn:aws:iam::xxxxxxxxx:instance-profile/nodes.xw-cluster-1.k8s.local
```
In the scenario where we would like to specify an AssumeRole using a roleArn, we would run `pulumi config set --path aws:assumeRole.roleArn arn:aws:iam::xxxxxxxxx:role/nodes.xw-cluster-1.k8s.local` and it would automatically generate the config in Pulumi.<stack-name>.yaml. This auto-generated config does not work when it  is placed under a Stack yaml file.
```
error validating data: ValidationError(Stack.spec.config.aws:assumeRole): invalid type for com.pulumi.v1alpha1.Stack.spec.config: got "map", expected "string"
```
## Steps to reproduce

git clone https://github.com/pulumi/pulumi-kubernetes-operator.git
cd pulumi-kubernetes-operator
git fetch --all --tags
git checkout tags/v0.0.17 -b v0.0.17
kubectl apply -f deploy/crds/
kubectl apply -f deploy/yaml
create a Stack yaml (named stack.yaml) with the config shown in the above
create github repo with pulumi project
point Stack yaml to github repo

kubectl apply -f stack.yaml

Expected: 
Be able to configure an AssumeRole for pulumi POD to utilize the IAM role on the host
Actual: 
Failing because `config` only accepts strings and not maps
