### ISSUE TITLE
Stack status output is leaking secrets.

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi-kubernetes-operator#204]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

If I run `pulumi stack output` the secrets are redacted. However, they are still in clear text in the stack output status.

### Steps to reproduce

My stack config is:

```
apiVersion: pulumi.com/v1alpha1
kind: Stack
...
spec:
  backend: s3://cloud-pulumi-state
  branch: refs/heads/master
...
  projectRepo: git@github.com:tetrateio/tetrate.git
  repoDir: cloud/projects/operations/storage/aws
  secretsProvider: <REDACTED>
  stack: operations.storage.aws
  useLocalStackOnly: true
```
