### ISSUE TITLE
Allow the ability to run a stack with a custom service account/role

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes-operator#241]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently the operator service account is the same account used to run the relevant stacks. It would be ideal to allow each stack to specify the service account it should use.
e.g.:
```
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: nginx-k8s-stack
spec:
...
  stack: "vivek/example/dev"
  projectRepo: https://github.com/viveklak/example
  branch: "refs/heads/master"
  destroyOnFinalize: true
  serviceAccount: <sa> # or
  role: <role>
```

This will probably require running the operator with a clusterrole but then "dropping privileges" to the appropriate serviceAccount/role. We may also need to consider a means to limit which roles to allow the operator to use - i.e. this is the logical equivalent of assume role in IAM in some ways and has similar security considerations.
