### ISSUE TITLE
Failed to update Stack status with default permalink

### ISSUE THREAD

**Issue by lghinet** [pulumi/pulumi-kubernetes-operator#254]
hello 
I got the following error using the operator with https://github.com/lghinet/pulumi_demo  stack 

```
{"level":"debug","ts":"2022-03-03T12:39:03.286Z","logger":"controller_stack","msg":"Adding Finalizer for the Stack","Request.Namespace":"pulumi","Request.Name":"pulumi-demo-stack","Stack.Name":"pulumi-demo-stack"}
{"level":"error","ts":"2022-03-03T12:39:07.320Z","logger":"controller_stack","msg":"Failed to update Stack status with default permalink","Request.Namespace":"pulumi","Request.Name":"pulumi-demo-stack","Stack.Name":"totalsoft/nginx/dev3","error":"Stack.pulumi.com \"pulumi-demo-stack\" is invalid: status.lastUpdate.lastResyncTime: Invalid value: \"null\": status.lastUpdate.lastResyncTime in body must be of type string: \"null\"","stacktrace":"github.com/pulumi/pulumi-kubernetes-operator/pkg/controller/stack.(*ReconcileStack).Reconcile\n\t/home/runner/work/pulumi-kubernetes-operator/pulumi-kubernetes-operator/pkg/controller/stack/stack_controller.go:255\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"}
{"level":"error","ts":"2022-03-03T12:39:08.141Z","logger":"controller-runtime.manager.controller.stack-controller","msg":"Reconciler error","name":"pulumi-demo-stack","namespace":"pulumi","error":"Stack.pulumi.com \"pulumi-demo-stack\" is invalid: status.lastUpdate.lastResyncTime: Invalid value: \"null\": status.lastUpdate.lastResyncTime in body must be of type string: \"null\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"}
{"level":"info","ts":"2022-03-03T12:39:08.141Z","logger":"controller_stack","msg":"Reconciling Stack","Request.Namespace":"pulumi","Request.Name":"pulumi-demo-stack"}

```

1. install the 1.4.0 pulumi operator on a 1.16 kubernetes  cluster 
2. create stack CR  
```
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: pulumi-demo-stack
  namespace: pulumi
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        namespace: pulumi
        key: accessToken
    ARM_CLIENT_SECRET:
      type: Secret
      secret:
        name: azure-secret
        namespace: pulumi
        key: ARM_CLIENT_SECRET
  stack: totalsoft/nginx/dev3
  projectRepo: https://github.com/lghinet/pulumi_demo
  commit: 78019a2a7376eef7cf40dfdce723a6f58756322f
  destroyOnFinalize: false
```
3. get operator logs 

any ideas ? 

thanks
