### ISSUE TITLE
Support for structured config

### ISSUE THREAD

**Issue by shailsirohi** [pulumi/pulumi-kubernetes-operator#258]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi supports [structured configuration](https://www.pulumi.com/docs/concepts/config/#structured-configuration) which allows using `config.GetObject`. This is really a great feature to represent arrays as yaml array and represent the entire config as go struct.
Currently Stack object config field is of type map[string]string. Having support for yaml arrays and object will be helpful.

The value would assumedly come from any of the supported sources, mainly:
- a literal YAML-encoded (or JSON-encoded) string
- a `Secret` with a key containing a YAML-encoded string

Ideally this feature would be orthogonal to whether or not the value is Pulumi secret.

There may be need for a new configuration block to allow for non-secret structured configuration. Note that `secretsRef` defines _Pulumi secrets_ from a secret or from a literal value, while non-secrets are simply typed as `map[string]string`.

Note that the Automation API recently added support for structured configuration: https://github.com/pulumi/pulumi/pull/12265

### Examples
_Some examples for discussion purposes._

These examples assume the following program:
```ts
interface Data {
    active: boolean;
    nums: number[];
}

let config = new pulumi.Config();
let data = config.requireObject<Data>("mydata");
console.log(`Active: ${data.active}`);
```
And intend to generate the following stack configuration:
```yaml
# Generated: Pulumi.dev.config
config:
  proj:mydata:
    active: true
    nums:
    - 1
    - 2
    - 3
```

Using a YAML value from a Kubernetes `Secret` as a Pulumi secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
stringData:
  data.yaml: |
    active: true
    nums:
    - 10
    - 20
    - 30
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: example-1
spec:
  stack: example/proj/dev
  config:
    aws:region: us-east-2
  secretsRef:
    mydata:
      type: secret
      secret:
        name: example-secret
        key: data.yaml
        type: object
  ...
```

Using an inline YAML value as a Pulumi secret:
```yaml
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: example-1
spec:
  stack: example/proj/dev
  config:
    aws:region: us-east-2
  secretsRef:
    mydata:
      type: literal
      literal:
        jsonValue:
          active: true
          nums:
          - 10
          - 20
          - 30
  ...
```

Using inline YAML as a non-secret (via a hypothetical `config2` block):
```yaml
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: example-1
spec:
  stack: example/proj/dev
  config:
    aws:region: us-east-2
  config2:
    mydata:
      jsonValue:
        active: true
        nums:
        - 10
        - 20
        - 30
  ...
```

### Open Questions
1. Config values are currently typed as `string` as opposed to `apiextensionsv1.JSON`.  If we were to change the API to use `JSON`, then the values would be interpreted as JSON values (e.g. `true` would become a bool).  Is that an acceptable (breaking) change? Or should a `jsonValue` field be introduced?  Or should literals be string-encoded? Note that `Program.spec.configuration.default` is a JSON value (not encoded).
2. Should the API types use `json.RawMessage` rather than `apiextensionsv1.JSON`?  See [Grafana](https://github.com/grafana-operator/grafana-operator/blob/50382a730d4c6c264b9dfa8e799d71fd5a06bee5/api/v1beta1/grafanadatasource_types.go#L45-L49) and [Tanzu](https://github.com/vmware-tanzu/vm-operator/blob/dd394de2874eb3cd07a4e591b8cce47559dda60e/api/v1alpha2/virtualmachineclass_types.go#L201-L205) for examples.
