### ISSUE TITLE
Kubernetes Operator's Memory usage is higher > 2 Gi

### ISSUE THREAD

**Issue by rajendragosavi** [pulumi/pulumi-kubernetes-operator#262]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We have seen a spike in the memory usage of Pulumi kubernetes operator , at the time of stack creation.  The memory usage has spiked upto 2.5Gi.

The problem is - we are running this operator on a fargate node, so If the pod goes above resource mem limit , it restarts and goes into statelock scenario. Also requiring this much resources for the pod is quite costly when we have to run this operator in multiple namespaces. 

Any tips/workaround for this?

sharing my stack.yaml and a sample code here 

```yaml

apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: team-11-s3-eu-dev-mgmt-11
  namespace: testing-2
spec:
  backend: "s3://bucket"
  secretsProvider: "awskms:key"
  stack: "staxk"
  projectRepo: "repo"
  branch: "refs/heads/master"
  destroyOnFinalize: true
  refresh: true
  resyncFrequencySeconds: 60
  continueResyncOnCommitMatch: true
  gitAuth:
    accessToken:
      type: Secret
      secret:
        namespace: testing-2
        name: pulumi-git-secrets
        key: GIT_TOKEN
  config:
    region: eu-central-1
    sgName: pulumi-ec2-debugging-4
  
```

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws"
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/ec2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	corev1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/core/v1"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		conf := config.New(ctx, "")
		region := conf.Require("region")
		sgName := conf.Require("sgName")
		vpcID := conf.Require("vpcID")

		roleToAssumeARN := conf.Require("roleToAssumeARN")
		fmt.Println("roleToAssumeARN ################", roleToAssumeARN)
		provider, err := aws.NewProvider(ctx, "privileged", &aws.ProviderArgs{
			AssumeRole: &aws.ProviderAssumeRoleArgs{
				RoleArn:     pulumi.StringPtr(roleToAssumeARN),
				SessionName: pulumi.String("PulumiSession"),
				ExternalId:  pulumi.String("PulumiApplication"),
			},
			Region: pulumi.String(region),
		})

		if err != nil {
			return err
		}

		// Create a security group
		group, err := ec2.NewSecurityGroup(ctx, sgName, &ec2.SecurityGroupArgs{
			Description: pulumi.String("creating test sg for pulumi iam-role poc"),
			VpcId:       pulumi.String(vpcID),
			Ingress: ec2.SecurityGroupIngressArray{
				ec2.SecurityGroupIngressArgs{
					Protocol:   pulumi.String("tcp"),
					FromPort:   pulumi.Int(80),
					ToPort:     pulumi.Int(80),
					CidrBlocks: pulumi.StringArray{pulumi.String("0.0.0.0/0")},
				},
			},
		}, pulumi.Provider(provider))

		if err != nil {
			return err
		}

		fmt.Printf("********* Security Group details *********** %+v \n", group)


		// // Create a simple web server using the startup script for the instance.
		ec2instance, err := ec2.NewInstance(ctx, "web-server-www", &ec2.InstanceArgs{
			SubnetId: pulumi.String("subnet-ID"),
			Tags: pulumi.StringMap{"Name": pulumi.String("" +
				"")},
			InstanceType:        pulumi.String("t2.micro"), // t2.micro is available in the AWS free tier.
			VpcSecurityGroupIds: pulumi.StringArray{group.ID()},
			Ami:                 pulumi.String("ami-7cef1113"),
			UserData:            pulumi.String(`#!/bin/bash echo "Hello, World!" > index.html nohup python -m SimpleHTTPServer 80 &`),
		},pulumi.Provider(provider))

		fmt.Printf("********* EC2 Instance details ********** - %+v \n ",ec2instance)

		secretName := "secret" + "-" + ctx.Stack()
		k8sSecret, err := corev1.NewSecret(ctx, secretName, &corev1.SecretArgs{
			StringData: pulumi.StringMap{
				"Security-group-name": pulumi.StringInput(group.ID()),
				"ec2ID": pulumi.StringInput(ec2instance.ID()),
			},
		}, pulumi.DependsOn([]pulumi.Resource{group,ec2instance}))

		if err != nil {
			return err
		}
		// Export the name of the bucket
		ctx.Export("SecretRef", k8sSecret.ID())


		return nil
	})
}

```
