### ISSUE TITLE
Operator doesn't use new Pulumi config

### ISSUE THREAD

**Issue by skdltmxn** [pulumi/pulumi-kubernetes-operator#411]
### What happened?

Since I updated my Pulumi Kubernetes Operator to 1.11.1, it seems like the operator cannot fetch newly updated Pulumi config from git repo.

Say, I have following config:

```yaml
app:
  name: my-service
  repo: my-secret-repo
  version: v1
```

and, if I update version to `v2`, the operator cannot recognize that the version has been modified.
It keeps applying with `v1`.  
Only after I kill the operator pod and then newly spawned pod starts to see `v2`.

This doesn't happen in v1.11.0.

### Expected Behavior

The operator should correctly apply newly updated Pulumi config

### Steps to reproduce

1. Deploy Pulumi Kubernetes Operator v1.11.1
2. Sync Kubernetes using the initial Pulumi config
3. Update Pulumi config in any way.
4. The operator doesn't see new config

### Output of `pulumi about`

```
CLI
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.29.1
azuread     5.34.0
kubernetes  3.24.0
nodejs      unknown

Host
OS       debian
Version  11.5
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v16.18.0'

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /tmp/pulumi-working/pulumi/pulumi-central-stack/yarn.lock or /tmp/pulumi-working/pulumi/pulumi-central-stack/package-lock.json
warning: A new version of Pulumi is available. To upgrade from version '3.46.0' to '3.54.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

I ran the command directly from the pod

### Additional context

This is my Stack with some irrelevant values redacted.

```yaml
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  labels:
    app.kubernetes.io/instance: pulumi-central-stack
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: pulumi-central-stack
  name: pulumi-central-stack
  namespace: pulumi
spec:
  backend: s3://XXX
  branch: refs/heads/main
  continueResyncOnCommitMatch: true
  destroyOnFinalize: false
  gitAuth:
    accessToken:
      secret:
        key: github_token
        name: pulumi-github-token
      type: Secret
  projectRepo: https://XXXX
  refresh: true
  resyncFrequencySeconds: 60
  stack: central
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
