### ISSUE TITLE
Also provide alternative image in `ghcr` registry?

### ISSUE THREAD

**Issue by budimanjojo** [pulumi/pulumi-kubernetes-operator#481]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Dockerhub's rate limits (100/6hours pull actions) is frustrating to deal with when you have a lot of containers. It would be great to also host the images on `ghcr` or maybe `quay.io`. The implementation should also be pretty easy looking at the current workflow that push the images. I believe it's as simple as adding these lines to this file: https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/.github/workflows/release.yaml

Below this:
https://github.com/pulumi/pulumi-kubernetes-operator/blob/7992cc99d8aed6056e1f68018fadbf21b92c6c6f/.github/workflows/release.yaml#L72-L74

Add this:
```
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

And then in this file: https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/.goreleaser.yml

Below this: https://github.com/pulumi/pulumi-kubernetes-operator/blob/7992cc99d8aed6056e1f68018fadbf21b92c6c6f/.goreleaser.yml#L58-L60

Add this:
```
    - "ghcr.io/pulumi/{{ .ProjectName }}:latest" 
    - "ghcr.io/pulumi/{{ .ProjectName }}:{{ .Tag }}"
```

I can do a PR if you don't have time to do this. Thanks before.
