### ISSUE TITLE
Support for backend authentication based on AWS IRSA

### ISSUE THREAD

**Issue by geowalrus4gh** [pulumi/pulumi-kubernetes-operator#558]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, backend authentication requires credentials to be passed as 'envRefs' in the Stack YAML. There are cases where long-running sessions are prohibited and are unable to configure the SESSION token in the envRefs. It would be better if the operator works with IRSA authentication when AWS is used.

**Comment by geowalrus4gh** [comment]
Sorry this was my mistake. I missed out the operator configuration part. If any one facing same issue, don't forget to add role to the service account in the operator helm chart. 
 ```
   image:
      registry: <docker-repo>
    serviceAccount:
      annotations:
        <role-arn>
```
