### ISSUE TITLE
Add `artifacthub-repo.yml` support for OCI artifact

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes-operator#582]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Implement this: https://artifacthub.io/docs/topics/repositories/helm-charts/#oci-support

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/pulumi-kubernetes-operator/issues/586

**Comment by dirien** [comment]
@EronWright:

You need to create this file `artifacthub-repo.yml` in the root of the yaml with following [content](https://artifacthub.io/docs/topics/repositories/#verified-publisher):

```yaml
# ID is for the OCI Image
repositoryID: 8fcdad40-fcf5-46af-a185-5ccbfa972b03
owners:
  - name: Engin Diri
    email: engin.diri@ediri.de
  - name: Eron Wright
    email: eron@pulumi.com
```

Thats it
