### ISSUE TITLE
Stop defaulting within the template blocks

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#704]
The type of the `StackSpec.workspaceTemplate` field should be an "apply" variant, similar to [k8s.io/client-go/applyconfigurations](https://pkg.go.dev/k8s.io/client-go/applyconfigurations#section-directories); it should not set any default values.  Otherwise it makes for noise in the higher-level APIs and overstates their intentions.

For example, when we apply a given stack:
```yaml
kind: Stack
spec:
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.134.1-nonroot
```

We get:

```yaml
kind: Stack
spec:
  workspaceTemplate:
    metadata: {}
    spec:
      image: pulumi/pulumi:3.134.1-nonroot
      resources: {}
      securityProfile: restricted
      serviceAccountName: default
```
