### ISSUE TITLE
Stack will not be deleted when prerequisite stack is missing

### ISSUE THREAD

**Issue by beffe123** [pulumi/pulumi-kubernetes-operator#751]
### What happened?

When you have two stacks where on (stack A) is a prerequsite of the other (stack B), then stack B can't be deleted after stack A has been deleted. In other words, order is not maintained during deletion and it is not fault tolerant.

### Example

1. create stack A (kubectl apply -f stack-a.yaml)
2. create stack B with stack A as a prerequisite (kubectl apply -f stack-b.yaml)
3. delete stack A (kubectl delete stack-a)
4. delete stack B (kubectl delete stack-b)

Output from 'kubectl describe stack-b':
```
...
Status:
  Conditions:
    Last Transition Time:  2024-11-18T16:11:42Z
    Message:               reconciliation is in progress
    Reason:                NotReadyInProgress
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-11-18T16:11:42Z
    Message:               unable to fetch prerequisite "stack-a": Stack.pulumi.com "stack-a" not found
    Reason:                PrerequisiteNotSatisfied
    Status:                True
    Type:                  Reconciling
...
```

### Output of `pulumi about`

n/a

### Additional context

Pulumi Operator versions tested:
- 1.16.0
- 1.14.0

This is especially a problem when using GitOps tools like Flux and ArgoCD.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment]
Thanks for the report, your finds ring true.  You're responsible for the lifecycle of the `Stack` objects, and nothing prevents you from deleting a prerequisite stack. 

Would a possible solution be to use Argo CD [sync waves](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/)? I believe that, by using two distinct waves, the ordering will be preserved during creation and deletion.  Could you give that a try?  For example:

```yaml
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: stack-a
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: stack-b
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  prerequisites:
    - name: stack-a
      requirement:
        succeededWithinDuration: 1m
```
