### ISSUE TITLE
Update CR failure message is not surfaced to Stack CR object

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-kubernetes-operator#806]
### What happened?

When an Update operation fails, the message/reason for failure is not surfaced back to the Stack CR object. This makes it hard for users to understand why a stack operation failed without diving into the logs, or the statuses of any Update CRs.

This occurs because we do not set the high level summary field for `Update.Status.Message`.

https://github.com/pulumi/pulumi-kubernetes-operator/blob/673ab77245d95556f5c9cb184c9024f384f72db3/operator/internal/controller/auto/update_controller.go#L288-L307

### Example

Current Stack status output which gives no details about why an update failed:

```
status:
  conditions:
  - lastTransitionTime: "2025-02-06T00:11:09Z"
    message: reconciliation is in progress
    reason: NotReadyInProgress
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-02-06T00:11:09Z"
    message: 2 update failure(s)
    reason: RetryingAfterFailure
    status: "True"
    type: Reconciling
  lastUpdate:
    failures: 2
    generation: 4
    lastAttemptedCommit: sha256:f335a9e0bc445b0dbe3187371f56017bcdd66e23b68c6eda54910eeb48d5e3a0
    lastResyncTime: "2025-02-06T00:14:27Z"
    lastSuccessfulCommit: sha256:f335a9e0bc445b0dbe3187371f56017bcdd66e23b68c6eda54910eeb48d5e3a0
    name: nginx-stack-194d89b9f33
    state: failed
    type: up
  observedGeneration: 4
  outputs:
    availableReplicas: 1
```

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
