### ISSUE TITLE
Support for ESC environments in the `Stack` custom resource

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-kubernetes-operator#814]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

A normal stack config file can contain two top level entries:

```yaml
config:
   <ns>:<key>: <value>
environment:
  - <name-of-esc-environment>
  - <name-of-other-esc-environment>
```

The current custom resource definition for `Stack` contains a property `config` that you can use to configure stack config values. But all usages of the word `environment` in the CRD yaml file refer to environment variables. As far as I can see from the CRD, there is no option to configure the list of ESC enviroments to use for the stack.

### Affected area/feature

PKO `Stack` CRD
