### ISSUE TITLE
Don't reclaim workspace during backoff

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes-operator#826]
When a stack update fails, the stack enters a backoff state. I think it desirable to retain the workspace in that case, e.g. for manual troubleshooting.  Note how `isSynced` may return true even the previous update was a failure.

If we really think that the workspace should be reclaimed during backoff, I would suggest that we change the policy API to cover each case.  Similar to statefulset.persistentVolumeClaimRetentionPolicy ([ref](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention)).
```yaml
workspaceReclaimPolicy:
  whenSuccessful: delete
  whenFailed: retain
```
