### ISSUE TITLE
Add support for storage backend 

### ISSUE THREAD

**Issue by omerlh** [pulumi/pulumi-kubernetes-operator#83]
Pulumi support storing the state in a backend similar to Terraform - AWS S3, GCS etc
The suggestion is to add support for this - allow to set in the secret, instead of access token, the relevant backend:
```
stringData:
  account: "gs://pulumi-state"
```

Looking at the code, this is relatively simple to add - unless there is a reason it is not there from the beginning :) 
This could also support on-prem deployments of pulumi - by setting the `account` key to the relevant server URL.

**Comment by lukehoban** [comment]
The changes to the Pulumi CLI proposed in https://github.com/pulumi/pulumi/pull/5789 would enable this to be accomplished with this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulumi-s3-backend
data:
  PULUMI_BACKEND_URL: s3://luke-s3-backend
---
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: s3-bucket-stack
spec:
  stack: lukehoban/operator-dev
  projectRepo: https://github.com/lukehoban/pytest1
  initOnCreate: true
  commit: 078124dae5f3c01e59619ee6947ee3cda260586b
  config:
    aws:region: us-west-2
  envs:
    - pulumi-s3-backend
```

In https://github.com/pulumi/pulumi-kubernetes-operator/pull/106 there is a proposed extension to the operator to make this more first-class.

```yaml
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: s3-bucket-stack
spec:
  backend: s3://luke-s3-backend
  stack: lukehoban/operator-dev
  projectRepo: https://github.com/lukehoban/pytest1
  initOnCreate: true
  commit: 078124dae5f3c01e59619ee6947ee3cda260586b
  config:
    aws:region: us-west-2
```
