### ISSUE TITLE
Occurence of `the object has been modified` on `Stack` resource

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-kubernetes-operator#836]
### What happened?

Customer sees this error after applying a `Stack` resource to the cluster:

```sh
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 2025-02-10T21:16:44.756Z	ERROR	Reconciler error	{"controller": "stack-controller", "namespace": "c1c824c-staging", "name": "s1-pko", "reconcileID": "8c3e1cd7-54f5-4291-9a1e-b947e2f96ea6", "error": "Operation cannot be fulfilled on stacks.pulumi.com \"s1-pko\": the object has been modified; please apply your changes to the latest version and try again"}
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 2025-02-10T21:16:44.786Z	ERROR	updating status	{"controller": "workspace-controller", "controllerGroup": "auto.pulumi.com", "controllerKind": "Workspace", "Workspace": {"name":"s1-pko","namespace":"c1c824c-staging"}, "namespace": "c1c824c-staging", "name": "s1-pko", "reconcileID": "1dc1b287-5cef-4865-aa1f-5289aec8cbcf", "revision": "171742985", "error": "Operation cannot be fulfilled on workspaces.auto.pulumi.com \"s1-pko\": the object has been modified; please apply your changes to the latest version and try again"}
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager github.com/pulumi/pulumi-kubernetes-operator/v2/operator/internal/controller/auto.(*WorkspaceReconciler).Reconcile.func1
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/operator/internal/controller/auto/workspace_controller.go:113
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager github.com/pulumi/pulumi-kubernetes-operator/v2/operator/internal/controller/auto.(*WorkspaceReconciler).Reconcile
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/operator/internal/controller/auto/workspace_controller.go:198
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:114
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:311
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 2025-02-10T21:16:44.786Z	ERROR	Reconciler error	{"controller": "workspace-controller", "controllerGroup": "auto.pulumi.com", "controllerKind": "Workspace", "Workspace": {"name":"s1-pko","namespace":"c1c824c-staging"}, "namespace": "c1c824c-staging", "name": "s1-pko", "reconcileID": "1dc1b287-5cef-4865-aa1f-5289aec8cbcf", "error": "Operation cannot be fulfilled on workspaces.auto.pulumi.com \"s1-pko\": the object has been modified; please apply your changes to the latest version and try again"}
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
pko-c1c824c-staging-controller-manager-6967cb6f75-pjcjt manager 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222
```

### Example

Customer applied this `Stack`:

```yaml
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: s1-pko
  namespace: c1c824c-staging
spec:
  serviceAccountName: pulumi-mateus
  branch: main
  envRefs:
    PULUMI_CONFIG_PASSPHRASE:
      literal:
        value: ""
      type: Literal
  gitAuth:
    accessToken:
      secret:
        key: password
        name: github-app-cloud-provisioning-bot-token
        namespace: c1c824c-staging
      type: Secret
  projectRepo: https://github.com/<redacted>/cloud-provisioning-recipes.git
  repoDir: /random-pet
  resyncFrequencySeconds: 300
  serviceAccountName: random-yaml
  stack: organization/random-pet/s1
```

### Output of `pulumi about`

Customer installed the operator via Helm:

```yaml
      chart: "./deploy/helm/pulumi-operator"
      git:
        tag: "v2.0.0-beta.3"
```

### Additional context

Related:

* #717 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
