### ISSUE TITLE
Workspace docker image repository is hard coded

### ISSUE THREAD

**Issue by project0** [pulumi/pulumi-kubernetes-operator#848]
### What happened?

I have configured the pulumi operator to use a different image (using ECR pull through cache) than the docker hub hosted default. 

However, it seem the image name (and version) used in the workspace is hard coded. 
Only way to change it to patch it via the workspace template. It does not seem a reliable way to me as one has to track changes in the operator during updates if there is a behavioral change how the workspace template is conducted. 

I can see multiple solutions: 
- the image is derived based on the running/deployed manifests (difficult to reflect)
- a configuration parameter in the operator itself
- the workspace spec allows setting the bootstrap and fetch image with something like "operatorImage" property (we have already `image`, but its serves a different purpose). I am aware of the named workspace template #797, but it would not solve the problem as describe initially. 

### Example

the final pod
```
apiVersion: v1
kind: Pod
spec:
  containers:
    ...
    # workspace image
    image: <id>.dkr.ecr.eu-central-1.amazonaws.com/cache/public.ecr.aws/pulumi/pulumi-go:3.147.0
    imagePullPolicy: IfNotPresent
    name: pulumi
  ...
  initContainers:
  - image: pulumi/pulumi-kubernetes-operator:v2.0.0
    name: bootstrap
    ...
  - image: pulumi/pulumi-kubernetes-operator:v2.0.0
    name: fetch
   ...
```

stack with workspace template:

```
apiVersion: pulumi.com/v1
kind: Stack
spec:
 
  workspaceTemplate:
    spec:
      image: <id>.dkr.ecr.eu-central-1.amazonaws.com/cache/public.ecr.aws/pulumi/pulumi-go:3.147.0
```

### Output of `pulumi about`

not relevant

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
