### ISSUE TITLE
Delete default keys from podTemplate to change volume type of "share" volume

### ISSUE THREAD

**Issue by luckyf** [pulumi/pulumi-kubernetes-operator#909]
### What happened?

Hi all,

due to some restrictions in the ephemeral storage of my K8s clusters, I need to **change the volume type of the "share" volume** in the Pulumi Stack podTemplate from `emptyDir` to `volumeClaimTemplate` (or any other volume type).
To make the examples shorter and easier to read, I used `persistentVolumeClaim` instead of `volumeClaimTemplate`.

My first try was to overwrite the volume definition like this

```yaml
# spec.workspaceTemplate.spec.podTemplate.spec
volumes:
  - name: share
    persistentVolumeClaim:
      name: xxx
  - name: additionalvolume
    # ...
```
but this results in the following object after getting merged with the default template. As K8s cannot derive which volume type to choose, it will not schedule the pod.
```yaml
# spec.workspaceTemplate.spec.podTemplate.spec
volumes:
  - name: share
    emptyDir: {} # <= This will be merged from the default workspaceTemplate
    persistentVolumeClaim:
      name: xxx
  - name: additionalvolume
    # ...
```

After some research on #774 and the [Strategic Merge Patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md) pattern I tried it like this but the `$patch` field does not match the CRD schema and therefore cannot be applied.

```yaml
# spec.workspaceTemplate.spec.podTemplate.spec
volumes:
  - name: share
    $patch: delete
  - name: share
    persistentVolumeClaim:
      name: xxx
  - name: additionalvolume
    # ...
```
Error message:
`Error from server (BadRequest): error when creating "stack.k8s.yml": Stack in version "v1" cannot be handled as a Stack: strict decoding error: unknown field "spec.workspaceTemplate.spec.podTemplate.spec.volumes[0].$patch", unknown field "spec.workspaceTemplate.spec.podTemplate.spec.volumes[1].volumeClaimTemplate"`

Is there any way to overwrite the volume type of the "share" volume inside of the podTemplate-Spec?
Thanks a lot in advance for the feedback.

### Example

Expected Result:

```yaml
# spec.workspaceTemplate.spec.podTemplate.spec
volumes:
  - name: share
    persistentVolumeClaim:
      name: xxx
  - name: additionalvolume
    # ...
```

### Output of `pulumi about`

not relevant

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
